name: flutter_purli
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  file_picker: ^10.1.4
  provider: ^6.1.1
  epub_parser: ^3.0.1
  supabase_flutter: ^2.3.3
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.2
  uni_links: ^0.5.1 # Keep original version constraint for reference

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  uni_links:
    path: ./overrides/uni_links-0.5.1

flutter:
  uses-material-design: true